[project]
name = "gametheory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "questionary>=2.1.1",
    "rich>=13.0.0",
]
[uv-package]
package = true
